name: Deploy xray Document
on:
  push:
    branches:
      - 'master'
  pull_request:
    types:
      - closed
jobs:
  push:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: up9cloud/action-rsync@master
        env:
          HOST: docs.xray.cool
          KEY: ${{secrets.DEPLOY_SSH_KEY}}
          TARGET: /home/github/xray_document
          ARGS: -avz --exclude=/.git/ --exclude=/.github/